apiVersion: v1
kind: Secret
metadata:
  name: acm-tmm-htpass-secret
  namespace: openshift-config
type: Opaque
data:
  htpasswd: {{hub fromSecret "openshift-config" "acm-tmm-htpass-secret" "htpasswd" hub}}
