apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: acm-htpasswd-provider 
    mappingMethod: claim 
    type: HTPasswd
    htpasswd:
      fileData:
        name: acm-htpass-secret
