apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-configure-acm-users
placementBindingDefaults:
  name: acm-tmm-idp-placement-binding
policyDefaults:
  namespace: policies
  placement:
    placementPath: input/placement.yaml
  orderPolicies: true
policies:
  - name: add-acm-tmm-hub-idp-provider
    manifests:
      - path: input/tmm-hub-idp.yaml
  - name: add-acm-tmm-hub-admin-cluster-role
    manifests:
     - path: input/tmm-hub-cluster-role.yaml 
  - name: remove-kubeadmin-password
    complianceType: "mustnothave"
    manifests:
      - path: input/remove-kubeadmin-pass.yaml
