apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-configure-acm-users
placementBindingDefaults:
  name: acm-tmm-idp-placement-binding
policyDefaults:
  namespace: policies
  orderPolicies: true
  placement:
    name: acm-tmm-idp-placement
    labelSelector:
      matchExpressions:
        - {key: vendor, operator: In, values: ["OpenShift"]}
        - {key: name, operator: NotIn, values: ["local-cluster"]}
policies:
  - name: add-acm-tmm-hub-idp-provider
    manifests:
      - path: input/tmm-hub-idp.yaml
#  - name: add-acm-tmm-hub-idp-provider
#    manifests:
#      - path: input/tmm-hub-cluster-role.yaml 
#  - name: remove-kubeadmin-password
#    complianceType: "mustnothave"
#    manifests:
#      - path: input/remove-kubeadmin-pass.yaml
