apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-configure-acm-users
placementBindingDefaults:
  name: acm-tmm-idp-placement-binding
policyDefaults:
  namespace: policies
  placement:
    placementPath: input/placement.yaml
policies:
  - name: add-acm-tmm-hub-idp-provider
    manifests:
      - path: input
        patches:
          - apiVersion: config.openshift.io/v1
            kind: OAuth
            metadata:
              name: cluster
            spec:
              identityProviders:
                - name: acm-tmm-htpasswd-provider 
                  mappingMethod: claim 
                  type: HTPasswd
                  htpasswd:
                    fileData:
                      name: acm-tmm-htpass-secret
#  - name: add-acm-tmm-hub-idp-provider
#    manifests:
#      - path: input/tmm-hub-cluster-role.yaml 
#  - name: remove-kubeadmin-password
#    complianceType: "mustnothave"
#    manifests:
#      - path: input/remove-kubeadmin-pass.yaml
